### ISSUE TITLE
Fuzzy matching support for `searchable`?

### ISSUE THREAD

**Issue by mondeja** [fabiospampinato/prask#3]
I'm wondering if you would accept PRs to implement fuzzy matching for `searchable` options.

**Comment by fabiospampinato** [comment]
Proooobably not, as I like that this package doesn't have any third-party dependencies, and I don't have a library that does fuzzy searching, but I've been meaning to open-source one I've written actually, if it's small enough (it probably is) I can wire the two together 👍 Give me a few days, I'm currently busy on other projects.

**Comment by uncenter** [comment]
Maybe the `searchable` option can accept a function to provide a custom search filterer? And then it is possible to use fuzzy searching (by using a fuzzy library inside said `searchable` custom function) without massively increasing bundle size?

**Comment by fabiospampinato** [comment]
That could also be an option 🤔

**Comment by mondeja** [comment]
Another option would be to use [`peerDependencies` + `peerDependenciesMeta`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#peerdependenciesmeta) with `optional: true`.

**Comment by fabiospampinato** [comment]
A bunch of [improvements](https://github.com/fabiospampinato/prask/commits/master/) shipped in v2.2. Relevant to this use case:

- The `string` and `number` prompts now have an optional `format` function, which can be used to style the user's input string. As I understand it this is something you guys missed for your color input.
- The `select` and `multiselect` prompts now support receiving options as a function that maps the current query to an array of options. This can be used to customize how results are ranked, and in combination with `searchable: false` this also allows you to customize how results are searched into and highlighted too. A limitation with this option is that the new array of options must be provided synchronously. As I understand it this should be good enough for you, right? Ideally it should support providing new options asynchronously also, but it gets a bit tricky because the user should be able to press more keys in the meantime, which is tricky to handle, so I haven't implemented that yet.
